//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace WechatApp.Tracking {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="logisticsTrackingSoap", Namespace="http://tempuri.org/")]
    public partial class logisticsTracking : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getLTRecordBySNOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXMLLTRecordBySNOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public logisticsTracking() {
            this.Url = global::WechatApp.Properties.Settings.Default.WechatApp_Tracking_logisticsTracking;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getLTRecordBySNCompletedEventHandler getLTRecordBySNCompleted;
        
        /// <remarks/>
        public event getXMLLTRecordBySNCompletedEventHandler getXMLLTRecordBySNCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLTRecordBySN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getLTRecordBySN(string serialNum) {
            object[] results = this.Invoke("getLTRecordBySN", new object[] {
                        serialNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLTRecordBySNAsync(string serialNum) {
            this.getLTRecordBySNAsync(serialNum, null);
        }
        
        /// <remarks/>
        public void getLTRecordBySNAsync(string serialNum, object userState) {
            if ((this.getLTRecordBySNOperationCompleted == null)) {
                this.getLTRecordBySNOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLTRecordBySNOperationCompleted);
            }
            this.InvokeAsync("getLTRecordBySN", new object[] {
                        serialNum}, this.getLTRecordBySNOperationCompleted, userState);
        }
        
        private void OngetLTRecordBySNOperationCompleted(object arg) {
            if ((this.getLTRecordBySNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLTRecordBySNCompleted(this, new getLTRecordBySNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getXMLLTRecordBySN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getXMLLTRecordBySN(string serialNum) {
            object[] results = this.Invoke("getXMLLTRecordBySN", new object[] {
                        serialNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getXMLLTRecordBySNAsync(string serialNum) {
            this.getXMLLTRecordBySNAsync(serialNum, null);
        }
        
        /// <remarks/>
        public void getXMLLTRecordBySNAsync(string serialNum, object userState) {
            if ((this.getXMLLTRecordBySNOperationCompleted == null)) {
                this.getXMLLTRecordBySNOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXMLLTRecordBySNOperationCompleted);
            }
            this.InvokeAsync("getXMLLTRecordBySN", new object[] {
                        serialNum}, this.getXMLLTRecordBySNOperationCompleted, userState);
        }
        
        private void OngetXMLLTRecordBySNOperationCompleted(object arg) {
            if ((this.getXMLLTRecordBySNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXMLLTRecordBySNCompleted(this, new getXMLLTRecordBySNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getLTRecordBySNCompletedEventHandler(object sender, getLTRecordBySNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLTRecordBySNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLTRecordBySNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getXMLLTRecordBySNCompletedEventHandler(object sender, getXMLLTRecordBySNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXMLLTRecordBySNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXMLLTRecordBySNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591